apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: testpmd-benchmark
  namespace: benchmark-operator
spec:
  clustername: myk8scluster
  workload:
    name: testpmd
    args:
      privileged: ${PRIVILEGED}
      pin: ${PIN}
      pin_testpmd: ${PIN_TESTPMD}
      pin_trex: ${PIN_TREX}
      networks:
        testpmd:
          - name: ${NETWORK_NAME}
            count: ${TESTPMD_NETWORK_COUNT}
        trex:
          - name: ${NETWORK_NAME}
            count: ${TREX_NETWORK_COUNT}

