apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: testpmd-benchmark
  namespace: benchmark-operator
spec:
  clustername: myk8scluster
  workload:
    name: testpmd
    args:
      privileged: true
      pin: true
      pin_testpmd: "worker000-fc640"      
      pin_trex: "worker002-fc640"      
      networks:
        testpmd:
          - name: testpmd-sriov-network
            count: 2  # Interface count, Min 2
        trex:
          - name: testpmd-sriov-network
            count: 2

