---

apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: oslat
  namespace: benchmark-operator
spec:
  elasticsearch:
    server: <ES_SERVER>
  workload:
    name: "oslat"
    args:
      runtime: "1m"
      disable_cpu_balance: true
      use_taskset: true
      pod:
        requests:
          memory: "200Mi"
          cpu: "4"
        limits:
          memory: "200Mi"
          cpu: "4"
